from contextlib import AbstractContextManager
from typing import Any

class _Scope:
    def set_tag(self, key: str, value: str) -> None: ...

def init(*, dsn: str) -> None: ...
def add_breadcrumb(*, category: str, level: str, message: str, data: dict[str, Any] | None = ...) -> None: ...
def capture_exception(error: BaseException) -> None: ...
def isolation_scope() -> AbstractContextManager[_Scope]: ...
