from contextlib import AbstractContextManager
from typing import Any

class _Scope:
    def set_tag(self, key: str, value: str) -> None: ...
    def add_breadcrumb(self, *, category: str, level: str, message: str, data: dict[str, Any]) -> None: ...

def init(
    *,
    dsn: str,
    transport: Any | None = ...,
    default_integrations: bool = ...,
    integrations: list[Any] = ...,
    traces_sample_rate: float = ...,
    auto_enabling_integrations: bool = ...,
) -> None: ...
def add_breadcrumb(*, category: str, level: str, message: str, data: dict[str, Any] | None = ...) -> None: ...
def capture_exception(error: BaseException) -> None: ...
def flush(timeout: float | None = ...) -> None: ...
def isolation_scope() -> AbstractContextManager[_Scope]: ...
def new_scope() -> AbstractContextManager[_Scope]: ...
